on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      - if: matrix.os == 'ubuntu-latest'
        run: sudo snap install snapcraft --classic
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ vars.SNAPCRAFT_STORE_CREDENTIALS }}
      - run: env
      - run: bun run build:electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
